# Support Vector Machine (C)

In [1]:
#Imoporting Libraries required
import numpy as np
import pandas as pd


%matplotlib inline

In [2]:
#Reading Dataset
df = pd.read_csv('BankNote_Authentication.csv')

In [3]:
#Shape of Dataset
df.shape

(1372, 5)

In [4]:
#Class wise segregation
df['class'].value_counts()

0    762
1    610
Name: class, dtype: int64

In [5]:
#Checking whether Null Values Exists
df.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [6]:
#Segregating Independent & Dependent Variables. X contains Independent & y contains Variable(s)
X = df.iloc[:, 0:3].values
y = df.iloc[:, 4].values

In [7]:
#Displaying variable X
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ],
       [  4.5459 ,   8.1674 ,  -2.4586 ],
       [  3.866  ,  -2.6383 ,   1.9242 ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ],
       [ -2.5419 ,  -0.65804,   2.6842 ]])

In [8]:
#Displaying variable y
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [9]:
#Splitting dataset for Training and Testing.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
#standardizing the data
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [11]:
print("X_train shape: ", X_train.shape)
print("X_test shape: ", X_test.shape)

X_train shape:  (1097, 3)
X_test shape:  (275, 3)


In [12]:
#Importing Support Vector MAchine (Classifier)
from sklearn.svm import SVC

classifier_SVC = SVC(probability=True)
classifier_SVC.fit(X_train,y_train)

SVC(probability=True)

In [13]:
#y_pred contains the predicted values
y_pred = classifier_SVC.predict(X_test)

In [14]:
#Comparing the actual and predicted values
df = pd.DataFrame({'Actual':y_test.flatten() , 'Predicted':y_pred.flatten()})
df.head(10)

Actual  Predicted
0       1          1
1       0          0
2       1          1
3       0          0
4       0          0
5       0          0
6       0          0
7       0          0
8       1          1
9       1          1

In [15]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

ac_SVM = accuracy_score(y_test,y_pred) * 100
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)
print(f"Accuracy : {ac_SVM}\n-----------------------------------------")
print(f"Confusion Matrix : \n{cm}\n-------------------------------------")
print(f"\nClassification Report : \n{cr}")

Accuracy : 99.63636363636364
-----------------------------------------
Confusion Matrix : 
[[156   1]
 [  0 118]]
-------------------------------------

Classification Report : 
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       157
           1       0.99      1.00      1.00       118

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

